#pragma once

enum OptionMainMenu {
	DEFAULT_MAIN_MENU = 0,
	SHOW_MUSIC_FROM_FOLDER,
	CREATE_PLAYLIST,
	DELETE_PLAYLIST,
	SHOW_PLAYLIST,
	UPDATE_PLAYLIST,
	SHOW_MEDIA_FILE,
	PLAY_OPTIONS,
	CHANGE_VOLUME,
	EXIT_MAIN_MENU
};

enum OptionUpdatePlaylistMenu {
	DEFAULT_UPDATE_PLAYLIST = 0,
	INSERT_MUSIC,
	DELETE_MUSIC,
	UPDATE_MEDIA_FILE
};

enum OptionUpdateMediaFileMenu {
	DEFAULT_MEDIA_FILE = 0,
	CHANGE_NAME,
	CHANGE_ARTIST,
	CHANGE_GENRE,
	CHANGE_YEAR
};

enum OptionPlayMusicMenu {
	DEFAULT_PLAY_MUSIC = 0,
	PLAY,
	PAUSE,
	RESUME,
	NEXT_MUSIC,
	PREVIOUS_MUSIC,
	PLAY_AUTOMATIC,
	STOP_AUTOMATIC
};

enum OptionPageMenu {
	DEFAULT_PAGE = 0,
	NEXT_PAGE,
	PREVIOUS_PAGE,
	PICK_PATH,
	EXIT_PAGE_MENU
};

enum OptionChangeVolume {
	DEFAULT_VOLUME = 0,
	INCREASE_VOLUME,
	DECREASE_VOLUME
};
